SurveyProject/SurveyProject/urls.py
from django.contrib import admin
from django.urls import path
from survey import views

urlpatterns = [path("admin/", admin.site.urls), path("", views.index)]

Tracker/urls.py
from django.contrib import admin
from django.urls import path, include   

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('gantt_chart.urls')),
    path("users/", include('users.urls'))
]

#kjksajdklfjaskdf

gantt_chart/urls.py
from django.urls import path
from . import views
from .views import Index

app_name = 'gantt_chart'
urlpatterns = [
    path('schedule/', views.chart, name = 'chart'),
    path("", Index.as_view(), name = "index"),
    path('new-task/', views.add_task, name = "add_task"),
    path('edit-task/<int:task_id>/', views.edit_task, name ="edit_task"),
    path('tasks/', views.task_list, name = "task_list"),
    path('my-tasks/', views.my_tasks, name = 'my_tasks'),
]

#this is a test

users/urls.py
from django.urls import path, include


app_name = 'users'
urlpatterns = [
    #Default auth urls
    path("", include('django.contrib.auth.urls')),
]

gantt_chart/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    responsible = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    weeks_left = models.CharField(max_length=2, blank = True)

    def __str__(self):
        return str(self.name)
    
    def save(self, *args, **kwargs):
        print(f'{self.end_date.isocalendar()[1] - self.start_date.isocalendar()[1]}')
        if self.weeks_left == "":
            self.weeks_left = f'{self.end_date.isocalendar()[1] - self.start_date.isocalendar()[1]}'
        super().save(*args, **kwargs)

gantt_chart/forms.py
from django import forms
from .models import Task

class DateInput(forms.DateInput):
    input_type = 'date'

class NewTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'responsible', 'start_date', 'end_date']
        widgets = {
            'start_date':DateInput(),
            'end_date':DateInput(),
        }

gantt_chart/views.py
from django.shortcuts import render, redirect
from .models import Task
import pandas as pd
import plotly.express as px
from plotly.offline import plot
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.decorators import login_required
from .forms import NewTaskForm

# Create your views here.

class Index(TemplateView):
    template_name = "index.html"



@login_required
def chart(request):
    qs = Task.objects.all()

    #data about each task
    tasks_data = [
        {
        'Name': x.name,
        'Responsible': x.responsible,
        'Start_date': x.start_date,
        'End_date': x.end_date,
        'Weeks_left': x.weeks_left,
        
        } for x in qs
    ]
    #Move data of each task to data frame
    df = pd.DataFrame(tasks_data)

    #plot the Gantt chart
    fig = px.timeline(
        df, x_start='Start_date', x_end='End_date', y='Name', color='Responsible',
        )
    
    fig.update_yaxes(autorange = "reversed")
    gantt_plot = plot(fig, output_type = 'div')
    
    #data transfered to the html page
    context = {'plot_div': gantt_plot}
    return render(request, 'chart.html', context)


def task_list(request):
    tasks = Task.objects.all()
    context = {'tasks':tasks}
    return render(request, 'gantt_chart/task_list.html', context)

@login_required
def add_task(request):
    if request.method != 'POST':
        form = NewTaskForm()
    else:
        form = NewTaskForm(data = request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.creator = request.user
            new_task.save()
            return redirect('gantt_chart:chart')
        
    context = {'new_task':form}
    return render(request, 'gantt_chart/add_task.html', context)



def edit_task(request, task_id):
    #Choose the task you want to edit
    task = Task.objects.get(id=task_id)

    if request.method != "POST":
        form = NewTaskForm(instance=task)
    else: 
        form = NewTaskForm(instance=task, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('gantt_chart:chart')
        
    context = {'task':task, 'form':form}
    return render(request, 'gantt_chart/edit_task.html', context)

def my_tasks(request):
    tasks = Task.objects.filter(responsible = request.user).order_by('end_date')
    context = {'my_tasks':tasks}
    return render(request, 'gantt_chart/my-tasks.html', context)    


    
def comment(request):
    print("test")

gantt_chart/templates/gantt_chart/add_task.html
{%extends 'gantt_chart/base.html'%}
{% load bootstrap5 %}
{%block content%}
	<div class="container" style="max-width:600px">
		<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
			<h1 class="display-4">New task</h1>
		</div>
		<div class="py-5">
			<div class="row">
				<div class="col-12">
					<form method="post" action="{% url 'gantt_chart:add_task' %}">
						{% csrf_token %}
						{% bootstrap_form new_task %}
						<button name="submit">Submit</button>
						<input type="hidden" name="next" value="{% url 'gantt_chart:chart' %}" />
					</form>
				</div>
			</div>
		</div>
	</div>
{%endblock content%}

gantt_chart/templates/gantt_chart/base.html
{% comment %} {% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>CONESU Project</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>
  
  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'learning_logs:index'%}">Study tracker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'learning_logs:topics' %}">courses</a>
            </li>
          </ul>
        </div>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a>Hello, {{ user.username }}! </a>&nbsp &nbsp</li>
            <li><a href="{% url 'users:logout' %}"> Log out</a></li>
          {% else %}
            <li><a href="{% url 'users:register' %}">Register</a>&nbsp &nbsp</li>
            <li><a href="{% url 'users:login' %}"> Log in  </a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    
    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   {% endcomment %}

   
   {% load bootstrap5 %}

   <!DOCTYPE html>
   <html lang="en">
     <head>
       <meta charset="utf-8">
       <meta http-equiv="X-UA-Compatible" content="IE=edge">
       <meta name="viewport" content="width=device-width, initial-scale=1">
   
       <title>CONESU Project</title>
   
       {% bootstrap_css %}
       {% bootstrap_javascript %}
   
     </head>
     
     <body>
   
       <!-- Static navbar -->
       <nav class="navbar navbar-expand-lg bg-body-tertiary">
         <div class="container-fluid">
          {% if user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'gantt_chart:chart'%}">CONESU</a>
           <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
           </button>
           <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'gantt_chart:chart' %}">Project Timeline</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'gantt_chart:my_tasks' %}">My tasks</a>
              </li>
            </ul>
          </div>
        {% else %}
        <a class="navbar-brand" href="{% url 'users:login'%}">CONESU</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'users:login' %}">Project Timeline</a>
            </li>
          </ul>
        </div>
        {% endif %}
           <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a>Hello, {{ user.username }}! </a>&nbsp &nbsp</li>
            <li><a href="{% url 'users:logout' %}"> Log out</a></li>
          {% endif %}
           </ul>
         </div>
       </nav>
       
       <div class="container">
   
         <div class="page-header">
           {% block header %}{% endblock %}
         </div>
         <div>
           {% block content %}{% endblock %}
         </div>
   
       </div> <!-- /container -->
   
     </body>
   </html>

gantt_chart/templates/gantt_chart/chart.html
{% extends 'base.html' %}
{% block content %}
        {% autoescape off %}
        {{plot_div}}
        {% endautoescape %}
        <h3><a class="btn btn-primary btn-lg" role="button" href="{% url 'gantt_chart:add_task'%} ">Add a new task</a></h3>
        <h3><a class="btn btn-primary btn-lg" role="button" href="{% url 'gantt_chart:task_list'%} ">Edit task</a></h3>
        
{% endblock content %}

gantt_chart/templates/gantt_chart/edit_task.html
{% extends 'gantt_chart/base.html' %}
{% load bootstrap5 %}

{% block content %}
  <div class="container" style="max-width:600px">
		<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
			<h1 class="display-4">Edit:{{task}}</h1>
    </div>
  </div>
  <div class="py-5">
    <div class="row">
      <div class="col-12">
        <form method="post" action="{% url 'gantt_chart:edit_task' task.id%}">
          {% csrf_token %}
          {% bootstrap_form form %}
          <button name="submit">Save changes</button>
          <input type="hidden" name="next" value="{% url 'gantt_chart:chart' %}" />
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

gantt_chart/templates/gantt_chart/index.html
{% extends "gantt_chart/base.html" %}

{% block header %}
  <div class='jumbotron'>
      <h1>CONESU.</h1>        
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:login' %}">Log In</a>development team
  </h2>
{% endblock content %}

{% comment "" %}THIS SHOULD BE A LANDING PAGE{% endcomment %}

gantt_chart/templates/gantt_chart/my-tasks.html
{% extends 'gantt_chart/base.html' %}
{% comment %} {% load 'bootstrap5' %} {% endcomment %}
{% block header %}
<div class="container" style="max-width:600px">
		<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
			<h1 class="display-4">My tasks</h1>
        </div>
</div>
{% endblock header %}

{% block content %}
<ul>
{% for task in my_tasks %}  
       <li class="list-group-item"> {{ task.name }} | {{ task.start_date|date }} - {{ task.end_date|date }}</a></li>
{% empty %}
    <li>No tasks to do.</li>
{% endfor %}
</ul>
{% endblock content %}

gantt_chart/templates/gantt_chart/task_list.html
{% extends 'gantt_chart/base.html' %}
{% load bootstrap5 %}

{% block header %}
<h1>Tasks</h1>
{% endblock header %}

{% block content %}
<ul class="list-group">
{% for task in tasks %}
    <li class="list-group-item"><a href = "{% url "gantt_chart:edit_task" task.id%}">    
        {{ task.name }} - {{ task.responsible }} - {{ task.end_date|date }}</a></li>
{% empty %}
    <li>No tasks to do.</li>
{% endfor %}
</ul>
{% endblock content %}